### PR TITLE
Add Cached reader

### PR DESCRIPTION
**Pull request by koriym**
Alternatives to the deprecated doctrine Cached Reader

See https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/CachedReader.php#L20

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, I don't have any knowledge about this, just noticed the linked file comment.

What about using suggested PsrCachedReader?
https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/PsrCachedReader.php

**Comment by koriym** [comment]
@TomasVotruba I thought I'd checked to see if they were available, but I'd missed that! Arigato.

**Comment by TomasVotruba** [comment]
@koriym I might be wrong, so please double check if the linked service does what you need.

It's possible it was added just recently. I do sometimes multiple PRs in a row, first deprecating, second removing old code, and only third to add a better solution.

Glad to help :+1:

**Comment by koriym** [comment]
Got it.

> I do sometimes multiple PRs in a row, first deprecating, second removing old code, and only third to add a better solution.

Interesting. Thank you for sharing. 👍

**Pull request closed without merging**
